// Compares a student's phonetic transcription against the expected phonetic
// generated by hebrewRules.js, and produces per-word and per-syllable scoring.

import { tokenizeWord, getExpectedPhonetic } from './hebrewRules.js'

// For a given syllable, compute all acceptable Latin-letter renderings.
// The set depends on the Hebrew vowel sign (not on tradition) — different
// transliteration conventions render the same vowel differently.
function syllableVariants(seg) {
  const c = seg.consonant ?? ''
  const base = seg.sound
  const vowel = seg.atom?.vowel
  const isFinal = !!seg.atom?.isFinal
  const out = new Set([base])

  if (vowel === 'tzere') {
    // tzere written as "e", "ei", "ey", "ay", "ai" — diphthong variants are
    // safe mid-word because they end in y/i (not a typical consonant)
    for (const v of ['e', 'ei', 'ey', 'ay', 'ai']) out.add(c + v)
  } else if (vowel === 'holam') {
    for (const v of ['o', 'oy', 'oi']) out.add(c + v)
    if (isFinal) out.add(c + 'oh') // "+oh" trailing only at word end
  } else if (vowel === 'qamats') {
    if (isFinal) out.add(c + 'ah') // "+ah" trailing only at word end
    if (base.endsWith('o')) out.add(c + 'aw') // Ashkenazic "aw" for kamatz
  } else if (vowel === 'patah') {
    if (isFinal) out.add(c + 'ah') // "+ah" trailing only at word end
  } else if (vowel === 'segol') {
    if (isFinal) out.add(c + 'eh') // "+eh" trailing only at word end
  }
  return [...out]
}

// Group expected segments into syllables: each syllable is one consonant + its
// vowel atom. We keep the original Hebrew chars per syllable for display.
function buildSyllables(atoms, segments) {
  return segments
    .filter(seg => seg.sound || seg.consonant || seg.vowel || seg.atom.letter)
    .map(seg => {
      const a = seg.atom
      // Reconstruct the display form: letter + nikud marks
      let display = a.letter
      const VOWEL_GLYPH = {
        'sheva':'ְ', 'hataf-segol':'ֱ', 'hataf-patah':'ֲ', 'hataf-qamats':'ֳ',
        'hiriq':'ִ', 'tzere':'ֵ', 'segol':'ֶ', 'patah':'ַ', 'qamats':'ָ',
        'holam':'ֹ', 'shuruk':'ּ', 'qubuts':'ֻ',
      }
      if (a.dagesh && a.letter !== 'ה') display += 'ּ' // dagesh
      if (a.letter === 'ה' && a.dagesh) display += 'ּ' // mappiq
      if (a.shinDot) display += 'ׁ'
      if (a.sinDot)  display += 'ׂ'
      if (a.vowel && VOWEL_GLYPH[a.vowel] && a.vowel !== 'shuruk') display += VOWEL_GLYPH[a.vowel]
      return {
        atomIndex: seg.atomIndex,
        atom: a,
        display,
        expected: seg.sound,
        consonant: seg.consonant,
        vowel: seg.vowel,
        shevaType: seg.shevaType,
        variants: syllableVariants(seg),
      }
    })
}

// Normalize student phonetic for matching. Folds common transliteration variants
// to the canonical form used by getExpectedPhonetic so the alignment doesn't
// false-flag innocent spelling differences.
//   tz, ts, tzh  → ts   (צ tsadi)
//   kh, x        → ch   (ח/כ guttural)
//   q            → k    (ק)
function normalizeStudent(phonetic) {
  return (phonetic ?? '')
    .toLowerCase()
    .replace(/[^a-z\s]/g, '')
    .replace(/\s+/g, ' ')
    .replace(/tzh/g, 'ts')
    .replace(/tz/g, 'ts')
    .replace(/kh/g, 'ch')
    .replace(/\bx/g, 'ch')
    .replace(/q/g, 'k')
    .trim()
}

// Greedy left-to-right alignment of expected sounds against student transcription.
// For each syllable, try to match its expected sound at the current student
// pointer. Allows small look-ahead skips (up to MAX_SKIP) to handle inserted
// sounds, but doesn't try to globally optimize.
const MAX_SKIP = 3

// Identify the phonological consonant unit at the start of `remaining`. Digraphs
// like "sh", "ch", "ts", "tz", "th", "kh" count as a single unit. Single
// consonant chars otherwise. Returns "" if remaining starts with a vowel.
const DIGRAPHS = ['sh', 'ch', 'ts', 'tz', 'th', 'kh']
function identifyConsonantUnit(remaining) {
  if (!remaining) return ''
  const two = remaining.slice(0, 2).toLowerCase()
  if (DIGRAPHS.includes(two)) return two
  const one = remaining[0]
  if (one && /[^aeiouy]/.test(one)) return one
  return ''
}

// Check if `expected` matches the start of `remaining` cleanly, without being
// part of a longer digraph. For example "s" should NOT match the start of "sh"
// because the "sh" is a single phonetic unit (shin sound). Same for "t" inside
// "ts"/"tz"/"th", "c" inside "ch", "k" inside "kh".
function cleanMatch(remaining, expected) {
  if (!remaining.startsWith(expected)) return false
  const after = remaining[expected.length] ?? ''
  const lastChar = expected[expected.length - 1]
  if (lastChar === 's' && after === 'h') return false  // would be "sh"
  if (lastChar === 't' && (after === 's' || after === 'z' || after === 'h')) return false
  if (lastChar === 'c' && after === 'h') return false
  if (lastChar === 'k' && after === 'h') return false
  return true
}

// Acceptable phonetic variants. Each expected sound may be transliterated
// multiple ways; we accept any of them as a clean match. Apply ONLY for
// boundary-sensitive sounds (diphthong endings, standalone y/i).
const SOUND_VARIANTS = {
  'y':  ['y', 'i'],   // word-final yod (chai/chay)
  'ay': ['ay', 'ai'],
  'oy': ['oy', 'oi'],
  'ey': ['ey', 'ei'],
}

// Try each acceptable variant of an expected sound against the start of `remaining`.
// Returns the variant string that matched, or null.
function matchAnyVariant(remaining, expected) {
  const variants = SOUND_VARIANTS[expected] ?? [expected]
  for (const v of variants) {
    if (cleanMatch(remaining, v)) return v
  }
  return null
}

// Same disambiguation but for indexOf (look-ahead matching)
function cleanIndexOf(haystack, needle) {
  let from = 0
  while (from <= haystack.length - needle.length) {
    const idx = haystack.indexOf(needle, from)
    if (idx === -1) return -1
    const after = haystack[idx + needle.length] ?? ''
    const last = needle[needle.length - 1]
    const isDigraph =
      (last === 's' && after === 'h') ||
      (last === 't' && (after === 's' || after === 'z' || after === 'h')) ||
      (last === 'c' && after === 'h') ||
      (last === 'k' && after === 'h')
    if (!isDigraph) return idx
    from = idx + 1
  }
  return -1
}

function nextSyllableCanStartAt(remaining, nextSyl) {
  if (!nextSyl) return true              // no next syllable — anything works
  if (!nextSyl.expected) return true     // next syllable is silent — anything works
  // Try any of next syllable's accepted variants
  for (const v of nextSyl.variants ?? [nextSyl.expected]) {
    if (cleanMatch(remaining, v)) return true
  }
  // Or at least its consonant
  if (nextSyl.consonant && cleanMatch(remaining, nextSyl.consonant)) return true
  return false
}

function alignSyllables(syllables, studentPhonetic) {
  const student = normalizeStudent(studentPhonetic).replace(/\s+/g, '')
  let pos = 0
  const matches = []

  for (let i = 0; i < syllables.length; i++) {
    const syl = syllables[i]
    const expected = syl.expected

    if (!expected) {
      matches.push({ ...syl, status: 'silent', heardAt: pos, heard: '' })
      continue
    }

    const remaining = student.slice(pos)
    // Look ahead to the next AUDIBLE syllable, skipping silent ones (alef/ayin,
    // final silent ה). A silent next syllable would pass any alignment check
    // vacuously, so we need to peek further.
    let nextSyl = null
    for (let j = i + 1; j < syllables.length; j++) {
      if (syllables[j].expected) { nextSyl = syllables[j]; break }
    }

    // Variant selection rule: prefer the SHORTEST variant whose tail leaves the
    // next syllable able to start. This stops a longer diphthong variant from
    // eating chars that belong to the next syllable. Example: רֹעִי "roi" — use
    // "ro" for cholam (not "roi"), so the chirik syllable can claim its "i".
    const variants = (syl.variants ?? [expected]).slice().sort((a, b) => a.length - b.length)
    let variantMatch = null
    let firstMatch = null
    for (const v of variants) {
      if (!cleanMatch(remaining, v)) continue
      if (!firstMatch) firstMatch = v
      if (nextSyllableCanStartAt(remaining.slice(v.length), nextSyl)) {
        variantMatch = v
        break
      }
    }
    if (!variantMatch) variantMatch = firstMatch                       // no aligned variant, take any
    if (!variantMatch) variantMatch = matchAnyVariant(remaining, expected)
    if (variantMatch) {
      // Check for vowel-elongation right after the matched syllable
      let elongated = ''
      const lastVowelChar = variantMatch.match(/[aeiouy]$/)?.[0]
      if (lastVowelChar) {
        const after = remaining.slice(variantMatch.length)
        while (elongated.length < 3 && after[elongated.length] === lastVowelChar) {
          elongated += lastVowelChar
        }
      }
      const status = elongated ? 'vowel-elongated' : 'matched'
      matches.push({
        ...syl,
        status,
        heardAt: pos,
        heard: variantMatch + elongated,
        vowelElongated: elongated,
      })
      pos += variantMatch.length + elongated.length
      continue
    }

    // Phase-by-phase matching: try consonant separately, then vowel separately.
    // This handles silent-consonant syllables (alef, ayin, final silent ה) and
    // prevents over-grabbing vowels that belong to the next syllable.
    let consumed = 0
    let heardConsonant = ''
    let heardVowel = ''
    let insertedBefore = '' // characters student inserted before the matched consonant
    let consonantMatched = !syl.consonant
    let vowelMatched = !syl.vowel

    // -- Consonant phase --
    if (syl.consonant) {
      const cMatch = matchAnyVariant(remaining, syl.consonant)
      if (cMatch) {
        heardConsonant = cMatch
        consumed += cMatch.length
        consonantMatched = true
      } else {
        // Lookahead: maybe the student inserted 1-2 consonants before the
        // expected consonant. If so, treat those as inserted-before chars and
        // still credit the syllable's consonant as matched.
        let skip = 0, laterMatch = null
        for (let k = 1; k <= 4 && k < remaining.length; k++) {
          const m = matchAnyVariant(remaining.slice(k), syl.consonant)
          if (m) { skip = k; laterMatch = m; break }
        }
        if (laterMatch) {
          insertedBefore = remaining.slice(0, skip)
          heardConsonant = laterMatch
          consumed += skip + laterMatch.length
          consonantMatched = true
        } else {
          // True mismatch — capture the digraph-aware consonant unit for reporting
          heardConsonant = identifyConsonantUnit(remaining)
          consumed += heardConsonant.length
        }
      }
    } else if (syl.vowel) {
      // No consonant expected (alef/ayin/silent final ה) but a vowel is.
      // Skim past any extra consonant the student inserted before the vowel.
      const vowelMatch = remaining.slice(0, 4).match(/[aeiouy]/)
      if (vowelMatch && vowelMatch.index > 0) {
        insertedBefore = remaining.slice(0, vowelMatch.index)
        consumed += vowelMatch.index
        consonantMatched = false // student inserted an unwanted consonant
      }
    }

    // -- Vowel phase --
    let vowelElongated = ''
    if (syl.vowel) {
      const afterConsonant = remaining.slice(consumed)
      const vMatch = matchAnyVariant(afterConsonant, syl.vowel)
      if (vMatch) {
        heardVowel = vMatch
        consumed += vMatch.length
        vowelMatched = true

        // Vowel-elongation: student held the vowel longer than written. Detect
        // by checking if the next char repeats the last vowel char we matched.
        const after = remaining.slice(consumed)
        const lastVowelChar = vMatch[vMatch.length - 1]
        let extra = 0
        while (
          extra < 3 &&
          after[extra] === lastVowelChar &&
          /[aeiouy]/.test(lastVowelChar)
        ) extra++
        if (extra > 0) {
          vowelElongated = after.slice(0, extra)
          consumed += extra
        }
      } else {
        const expectedVowelLen = syl.vowel.length
        const vowelChars = afterConsonant.match(/^[aeiouy]+/)?.[0] ?? ''
        heardVowel = vowelChars.slice(0, expectedVowelLen)
        consumed += heardVowel.length
      }
    }

    // Decide status from the phase results
    let status
    if (consonantMatched && vowelMatched) {
      if (insertedBefore) status = 'matched-with-insertion'
      else if (vowelElongated) status = 'vowel-elongated'
      else status = 'matched'
    } else if (consonantMatched && !vowelMatched) {
      status = syl.vowel ? 'vowel-mismatch' : (heardVowel ? 'extra-vowel' : 'matched')
    } else if (!consonantMatched && vowelMatched && !syl.consonant) {
      // Silent expected consonant but student inserted one before the vowel
      status = 'extra-consonant'
    } else {
      status = 'mismatch'
    }

    matches.push({
      ...syl,
      status,
      heardAt: pos,
      heard: insertedBefore + heardConsonant + heardVowel + vowelElongated,
      heardConsonant,
      heardVowel,
      insertedBefore,
      vowelElongated,
    })
    pos += Math.max(1, consumed)
  }

  // Track if the student transcription has trailing chars not consumed (might
  // be a sheva nach inserted or extra sound at end)
  const trailing = student.slice(pos)
  return { matches, trailing }
}

// Per-syllable score derivation from the match status.
function scoreSyllable(m, tradition, shevaMode) {
  // Silent atoms (e.g. final silent ה) always score 100
  if (m.status === 'silent') return { score: 100, note: '' }

  if (m.status === 'matched') return { score: 95, note: '' }

  if (m.status === 'matched-with-insertion') {
    return {
      score: 78,
      note: `Extra "${m.insertedBefore}" sound inserted before ${m.atom.letter} — should not be there.`,
    }
  }

  if (m.status === 'vowel-elongated') {
    return {
      score: 80,
      note: `Vowel held too long — the "${m.vowel}" sound should not be elongated to "${m.vowel}${m.vowelElongated}".`,
    }
  }

  if (m.status === 'matched-after-skip') return { score: 90, note: '' }

  if (m.status === 'extra-vowel') {
    // Probably a sheva nach that was pronounced as vocal
    if (m.shevaType === 'nach' && shevaMode === 'enforce') {
      return {
        score: 68,
        note: `Sheva nach should be silent — heard an inserted "${m.heardVowel}" sound.`,
      }
    }
    return { score: 90, note: '' } // benign extra vowel
  }

  if (m.status === 'vowel-mismatch') {
    // Consonant right, vowel different
    if (m.shevaType === 'na' && shevaMode === 'enforce' && !m.heardVowel) {
      return {
        score: 70,
        note: `Sheva na should be pronounced as a brief "uh" — the consonants ran together.`,
      }
    }
    return {
      score: 75,
      note: `Vowel mismatch — expected "${m.expected}", heard "${m.heard}".`,
    }
  }

  if (m.status === 'extra-consonant') {
    const L = m.atom.letter
    const which = L === 'ה' ? 'silent ה' : L === 'א' ? 'silent א (alef)' : L === 'ע' ? 'silent ע (ayin)' : L
    return {
      score: 70,
      note: `Extra "${m.insertedBefore}" sound inserted before ${which} — that letter is silent here.`,
    }
  }

  if (m.status === 'mismatch') {
    const note = buildMismatchNote(m, tradition)
    return { score: 60, note }
  }

  return { score: 80, note: '' }
}

function buildMismatchNote(m, tradition) {
  const heardC = m.heardConsonant || m.heard
  const expectedC = m.consonant
  const L = m.atom.letter

  // Specific known errors with explanatory notes
  if (L === 'ת' && expectedC === 't' && heardC.startsWith('s')) {
    return `ת should be "t" (${tradition}) — heard "s" instead.`
  }
  if (L === 'ת' && expectedC === 's' && heardC.startsWith('t')) {
    return `ת without dagesh should be "s" (Ashkenazic sav) — heard "t" instead.`
  }
  if (L === 'ש' && expectedC === 'sh' && heardC.startsWith('s')) {
    return `שׁ (shin) should be "sh" — heard "s" instead.`
  }
  if (L === 'ש' && expectedC === 's' && heardC.startsWith('sh')) {
    return `שׂ (sin) should be "s" — heard "sh" instead.`
  }
  if (L === 'ב' && expectedC === 'b' && heardC.startsWith('v')) {
    return `בּ (with dagesh) should be "b" — heard "v" instead.`
  }
  if (L === 'ב' && expectedC === 'v' && heardC.startsWith('b')) {
    return `ב (no dagesh) should be "v" — heard "b" instead.`
  }
  if ((L === 'פ' || L === 'ף') && expectedC === 'p' && heardC.startsWith('f')) {
    return `פּ (with dagesh) should be "p" — heard "f" instead.`
  }
  if ((L === 'פ' || L === 'ף') && expectedC === 'f' && heardC.startsWith('p')) {
    return `פ (no dagesh) should be "f" — heard "p" instead.`
  }
  if (L === 'ה' && expectedC === 'h' && !heardC) {
    return `ה with mappiq should be pronounced "h" — heard silence.`
  }
  if (L === 'ה' && !expectedC && heardC.startsWith('h')) {
    return `Final ה should be silent here — heard "h".`
  }
  // Generic
  if (m.heard) return `${L} should be "${m.expected}" — heard "${m.heard}".`
  return `${L} expected sound was not heard.`
}

// ── Public API ───────────────────────────────────────────────────────

// Score a single word: returns { word, score, errorType, phoneticHeard,
// expectedPhonetic, syllables: [{ phoneme, accuracyScore, note }] }
export function scoreWordAgainstTranscription(referenceWord, heardPhonetic, settings = {}) {
  const { tradition = 'sephardic', shevaMode = 'enforce' } = settings
  const atoms = tokenizeWord(referenceWord)
  const { segments, fullPhonetic } = getExpectedPhonetic(atoms, { tradition, shevaMode })
  const syllables = buildSyllables(atoms, segments)

  // Omission: no heard phonetic at all
  if (!heardPhonetic || normalizeStudent(heardPhonetic).length === 0) {
    return {
      word: referenceWord,
      score: 0,
      errorType: 'Omission',
      phoneticHeard: '',
      expectedPhonetic: fullPhonetic,
      syllables: syllables.map(s => ({
        phoneme: s.display,
        accuracyScore: 0,
        note: '',
      })),
    }
  }

  const { matches, trailing } = alignSyllables(syllables, heardPhonetic)

  const scoredSyllables = matches.map(m => {
    const { score, note } = scoreSyllable(m, tradition, shevaMode)
    return { phoneme: m.display, accuracyScore: score, note, _match: m }
  })

  // Penalize any trailing chars the student said after the word's expected end.
  // Attach the note to the last audible syllable so it's visible in the panel.
  if (trailing) {
    for (let i = scoredSyllables.length - 1; i >= 0; i--) {
      if (scoredSyllables[i]._match.expected) {
        const ex = scoredSyllables[i]
        const trailingNote = `Extra "${trailing}" sound at the end of the word — should not be there.`
        scoredSyllables[i] = {
          ...ex,
          accuracyScore: Math.min(ex.accuracyScore, 78),
          note: ex.note ? `${ex.note} ${trailingNote}` : trailingNote,
        }
        break
      }
    }
  }

  const avgScore = Math.round(
    scoredSyllables.reduce((s, x) => s + x.accuracyScore, 0) / scoredSyllables.length
  )
  const anyErrors = scoredSyllables.some(s => s.accuracyScore < 85)
  const errorType = anyErrors ? 'Mispronunciation' : 'None'

  // Strip the internal _match field before returning
  return {
    word: referenceWord,
    score: avgScore,
    errorType,
    phoneticHeard: heardPhonetic,
    expectedPhonetic: fullPhonetic,
    syllables: scoredSyllables.map(({ _match, ...rest }) => rest),
  }
}

// Score an entire utterance: word-by-word using provided per-word transcriptions.
export function scoreWords(referenceWords, perWordHeard, settings = {}) {
  return referenceWords.map((word, i) => scoreWordAgainstTranscription(word, perWordHeard[i] ?? '', settings))
}
