// Compares a student's phonetic transcription against the expected phonetic
// generated by hebrewRules.js, and produces per-word and per-syllable scoring.

import { tokenizeWord, getExpectedPhonetic } from './hebrewRules.js'

// For a given syllable, compute all acceptable Latin renderings of its vowel.
// The set depends on the Hebrew vowel sign (not on tradition) — different
// transliteration conventions render the same vowel differently. Variants that
// end in a letter which could start the next syllable ("oh", "uh") are safe
// because the aligner prefers the shortest variant that leaves the next
// syllable able to start.
function vowelVariants(seg) {
  const base = seg.vowel ?? ''
  if (!base) return ['']
  const vowel = seg.atom?.vowel
  const isFinal = !!seg.atom?.isFinal
  const out = new Set([base])

  if (vowel === 'tzere') {
    // tzere written as "e", "ei", "ey", "ay", "ai"
    for (const v of ['ei', 'ey', 'ay', 'ai']) out.add(v)
  } else if (vowel === 'holam') {
    // "oy"/"oi" (Ashkenazic), "oh"/"ow" (American spelling: "shalohm")
    for (const v of ['oy', 'oi', 'oh', 'ow']) out.add(v)
  } else if (vowel === 'qamats') {
    if (isFinal) out.add('ah') // "+ah" trailing only at word end
    if (base === 'o') { out.add('aw'); out.add('oh') } // Ashkenazic kamatz / qamats katan
  } else if (vowel === 'patah') {
    if (isFinal) out.add('ah') // "+ah" trailing only at word end
  } else if (vowel === 'segol') {
    if (isFinal) out.add('eh') // "+eh" trailing only at word end
  } else if (vowel === 'hiriq') {
    out.add('ee') // English spelling of "i" ("anee", "bereesheet")
    if (isFinal) out.add('iy')
  } else if (vowel === 'shuruk' || vowel === 'qubuts') {
    out.add('oo')
  } else if (vowel === 'sheva') {
    // Sheva na is a schwa — heard as "e", "eh", "u" or "uh"
    for (const v of ['eh', 'u', 'uh']) out.add(v)
    // Before yud it colors toward "i" (בְּיוֹם "biyom")
    if (seg.nextAtom?.letter === 'י') out.add('i')
  }
  return [...out]
}

// Group expected segments into syllables: each syllable is one consonant + its
// vowel atom. We keep the original Hebrew chars per syllable for display.
function buildSyllables(atoms, segments) {
  return segments
    .filter(seg => seg.sound || seg.consonant || seg.vowel || seg.atom.letter)
    .map(seg => {
      const a = seg.atom
      // Reconstruct the display form: letter + nikud marks
      let display = a.letter
      const VOWEL_GLYPH = {
        'sheva':'ְ', 'hataf-segol':'ֱ', 'hataf-patah':'ֲ', 'hataf-qamats':'ֳ',
        'hiriq':'ִ', 'tzere':'ֵ', 'segol':'ֶ', 'patah':'ַ', 'qamats':'ָ',
        'holam':'ֹ', 'shuruk':'ּ', 'qubuts':'ֻ',
      }
      if (a.dagesh && a.letter !== 'ה') display += 'ּ' // dagesh
      if (a.letter === 'ה' && a.dagesh) display += 'ּ' // mappiq
      if (a.shinDot) display += 'ׁ'
      if (a.sinDot)  display += 'ׂ'
      if (a.vowel && VOWEL_GLYPH[a.vowel] && a.vowel !== 'shuruk') display += VOWEL_GLYPH[a.vowel]
      const nextAtom = a.isFinal ? null : atoms[seg.atomIndex + 1]
      const vVariants = vowelVariants({ ...seg, nextAtom })
      const c = seg.consonant ?? ''
      return {
        atomIndex: seg.atomIndex,
        atom: a,
        display,
        expected: seg.sound,
        consonant: seg.consonant,
        vowel: seg.vowel,
        shevaType: seg.shevaType,
        patachGenuvah: !!seg.patachGenuvah,
        vowelVariants: vVariants,
        variants: vVariants.map(v => seg.patachGenuvah ? v + c : c + v),
      }
    })
}

// Normalize student phonetic for matching. Folds common transliteration variants
// to the canonical form used by getExpectedPhonetic so the alignment doesn't
// false-flag innocent spelling differences.
//   tz, ts, tzh  → ts   (צ tsadi)
//   kh, x        → ch   (ח/כ guttural)
//   q            → k    (ק)
//   j            → y    (German/academic "Jisrael" — Hebrew has no "j" sound)
//   w + vowel    → v    (academic "wayomer" for vav)
// Apostrophes for alef/ayin ("'esav") are dropped with the other punctuation.
function normalizeStudent(phonetic) {
  return (phonetic ?? '')
    .toLowerCase()
    .replace(/[^a-z\s]/g, '')
    .replace(/\s+/g, ' ')
    .replace(/tzh/g, 'ts')
    .replace(/tz/g, 'ts')
    .replace(/kh/g, 'ch')
    .replace(/\bx/g, 'ch')
    .replace(/q/g, 'k')
    .replace(/j/g, 'y')
    .replace(/w(?=[aeiou])/g, 'v')
    .trim()
}

// Greedy left-to-right alignment of expected sounds against student transcription.
// For each syllable, try to match its expected sound at the current student
// pointer. Allows small look-ahead skips (up to MAX_SKIP) to handle inserted
// sounds, but doesn't try to globally optimize.
const MAX_SKIP = 3

// Identify the phonological consonant unit at the start of `remaining`. Digraphs
// like "sh", "ch", "ts", "tz", "kh" count as a single unit. Single consonant
// chars otherwise. Returns "" if remaining starts with a vowel.
// Note: "th" deliberately NOT a digraph — in Hebrew transliteration the "t"
// and following "h" are almost always two separate sounds (e.g. ת ending
// one syllable, ה starting the next, as in "veethanefesh").
const DIGRAPHS = ['sh', 'ch', 'ts', 'tz', 'kh']
function identifyConsonantUnit(remaining) {
  if (!remaining) return ''
  const two = remaining.slice(0, 2).toLowerCase()
  if (DIGRAPHS.includes(two)) return two
  const one = remaining[0]
  if (one && /[^aeiouy]/.test(one)) return one
  return ''
}

// Check if `expected` matches the start of `remaining` cleanly, without being
// part of a longer digraph. For example "s" should NOT match the start of "sh"
// because the "sh" is a single phonetic unit (shin sound). Same for "t" inside
// "ts"/"tz"/"th", "c" inside "ch", "k" inside "kh".
function cleanMatch(remaining, expected) {
  if (!remaining.startsWith(expected)) return false
  const after = remaining[expected.length] ?? ''
  const lastChar = expected[expected.length - 1]
  if (lastChar === 's' && after === 'h') return false  // would be "sh"
  if (lastChar === 't' && (after === 's' || after === 'z')) return false  // ts/tz digraphs (but NOT th)
  if (lastChar === 'c' && after === 'h') return false
  if (lastChar === 'k' && after === 'h') return false
  return true
}

// Acceptable phonetic variants. Each expected sound may be transliterated
// multiple ways; we accept any of them as a clean match. Apply ONLY for
// boundary-sensitive sounds (diphthong endings, standalone y/i).
const SOUND_VARIANTS = {
  'y':  ['y', 'i'],   // word-final yod (chai/chay)
  'ay': ['ay', 'ai'],
  'oy': ['oy', 'oi'],
  'ey': ['ey', 'ei'],
}

// Try each acceptable variant of an expected sound against the start of `remaining`.
// Returns the variant string that matched, or null.
function matchAnyVariant(remaining, expected) {
  const variants = SOUND_VARIANTS[expected] ?? [expected]
  for (const v of variants) {
    if (cleanMatch(remaining, v)) return v
  }
  return null
}

// Pick which of a syllable's accepted variants the student said at the start of
// `remaining`: the SHORTEST one whose tail leaves the next syllable able to
// start, else the shortest that matches at all. This stops a longer variant
// from eating chars that belong to the next syllable. Example: רֹעִי "roi" —
// use "ro" for cholam (not "roi"), so the chirik syllable can claim its "i".
// With no audible syllable left, prefer the variant that ends the word ("aniy").
function pickVariant(remaining, variants, nextSyl) {
  let firstMatch = null
  for (const v of variants.slice().sort((a, b) => a.length - b.length)) {
    if (!v || !cleanMatch(remaining, v)) continue
    if (!firstMatch) firstMatch = v
    const tail = remaining.slice(v.length)
    if (nextSyl ? nextSyllableCanStartAt(tail, nextSyl) : tail === '') return v
  }
  return firstMatch
}

// Same disambiguation but for indexOf (look-ahead matching)
function cleanIndexOf(haystack, needle) {
  let from = 0
  while (from <= haystack.length - needle.length) {
    const idx = haystack.indexOf(needle, from)
    if (idx === -1) return -1
    const after = haystack[idx + needle.length] ?? ''
    const last = needle[needle.length - 1]
    const isDigraph =
      (last === 's' && after === 'h') ||
      (last === 't' && (after === 's' || after === 'z')) ||  // ts/tz only, NOT th
      (last === 'c' && after === 'h') ||
      (last === 'k' && after === 'h')
    if (!isDigraph) return idx
    from = idx + 1
  }
  return -1
}

function nextSyllableCanStartAt(remaining, nextSyl) {
  if (!nextSyl) return true              // no next syllable — anything works
  if (!nextSyl.expected) return true     // next syllable is silent — anything works
  // Try any of next syllable's accepted variants
  for (const v of nextSyl.variants ?? [nextSyl.expected]) {
    if (cleanMatch(remaining, v)) return true
  }
  // Or at least its consonant
  if (nextSyl.consonant && cleanMatch(remaining, nextSyl.consonant)) return true
  return false
}

function alignSyllables(syllables, studentPhonetic) {
  const student = normalizeStudent(studentPhonetic).replace(/\s+/g, '')
  let pos = 0
  const matches = []

  for (let i = 0; i < syllables.length; i++) {
    const syl = syllables[i]
    const expected = syl.expected

    if (!expected) {
      matches.push({ ...syl, status: 'silent', heardAt: pos, heard: '' })
      continue
    }

    // Look ahead to the next AUDIBLE syllable, skipping silent ones (alef/ayin,
    // final silent ה). A silent next syllable would pass any alignment check
    // vacuously, so we need to peek further.
    let nextSyl = null
    for (let j = i + 1; j < syllables.length; j++) {
      if (syllables[j].expected) { nextSyl = syllables[j]; break }
    }

    // Gemination: a doubled consonant ("vayyomer" for וַיֹּאמֶר, dagesh chazak)
    // sounds the same as a single one. Skip the extra copy unless the next
    // syllable legitimately starts with that same consonant.
    const c0 = student[pos]
    if (syl.consonant?.length === 1 && c0 === syl.consonant && student[pos + 1] === c0 &&
        nextSyl?.consonant?.[0] !== c0) {
      pos++
    }

    const remaining = student.slice(pos)

    let variantMatch = pickVariant(remaining, syl.variants ?? [expected], nextSyl)
    if (!variantMatch) variantMatch = matchAnyVariant(remaining, expected)
    if (variantMatch) {
      // Check for vowel-elongation right after the matched syllable, but ONLY
      // if the repeated vowel char wouldn't be the legitimate start of the next
      // audible syllable. Otherwise we'd eat the next syl's vowel (e.g. "veet"
      // for וְאֵת: the second "e" belongs to alef+segol, not to elongation).
      let elongated = ''
      const lastVowelChar = variantMatch.match(/[aeiouy]$/)?.[0]
      const nextStartsWithSameVowel =
        lastVowelChar && nextSyl?.expected && nextSyl.expected[0] === lastVowelChar
      if (lastVowelChar && !nextStartsWithSameVowel) {
        const after = remaining.slice(variantMatch.length)
        while (elongated.length < 3 && after[elongated.length] === lastVowelChar) {
          elongated += lastVowelChar
        }
      }
      const status = elongated ? 'vowel-elongated' : 'matched'
      matches.push({
        ...syl,
        status,
        heardAt: pos,
        heard: variantMatch + elongated,
        vowelElongated: elongated,
        consonantMatched: true,
        vowelMatched: true,
      })
      pos += variantMatch.length + elongated.length
      continue
    }

    if (syl.patachGenuvah) {
      const g = alignPatachGenuvah(syl, remaining)
      if (g) {
        const { consumed, ...rest } = g
        matches.push({ ...syl, ...rest, heardAt: pos })
        pos += Math.max(1, consumed)
        continue
      }
    }

    // Phase-by-phase matching: try consonant separately, then vowel separately.
    // This handles silent-consonant syllables (alef, ayin, final silent ה) and
    // prevents over-grabbing vowels that belong to the next syllable.
    let consumed = 0
    let heardConsonant = ''
    let heardVowel = ''
    let insertedBefore = '' // characters student inserted before the matched consonant
    let consonantMatched = !syl.consonant
    let vowelMatched = !syl.vowel

    // -- Consonant phase --
    if (syl.consonant) {
      let cMatch = matchAnyVariant(remaining, syl.consonant)

      // Soft-match fallback: cleanMatch refuses to match "t" when followed by
      // "s"/"z" (would form ts/tz digraph), and similarly for sh/ch/kh. But if
      // the next audible syllable's consonant starts with the digraph-completing
      // char, then the "extra" char rightfully belongs to that next syllable and
      // the digraph block is wrong here.
      // e.g. אֶת־שָׂרַי → "etsaray": the "ts" is really ת + שׂ, not צ.
      if (!cMatch && remaining.startsWith(syl.consonant)) {
        const afterChar = remaining[syl.consonant.length] ?? ''
        const lastC = syl.consonant[syl.consonant.length - 1]
        const wouldFormDigraph =
          (lastC === 't' && (afterChar === 's' || afterChar === 'z')) ||
          (lastC === 's' && afterChar === 'h') ||
          (lastC === 'c' && afterChar === 'h') ||
          (lastC === 'k' && afterChar === 'h')
        const nextC = nextSyl?.consonant?.[0]
        if (wouldFormDigraph && nextC === afterChar) {
          cMatch = syl.consonant
        }
      }

      if (cMatch) {
        heardConsonant = cMatch
        consumed += cMatch.length
        consonantMatched = true
      } else {
        // Lookahead: maybe the student inserted 1-2 consonants before the
        // expected consonant. If so, treat those as inserted-before chars and
        // still credit the syllable's consonant as matched.
        let skip = 0, laterMatch = null
        for (let k = 1; k <= 4 && k < remaining.length; k++) {
          const m = matchAnyVariant(remaining.slice(k), syl.consonant)
          if (m) { skip = k; laterMatch = m; break }
        }
        if (laterMatch) {
          insertedBefore = remaining.slice(0, skip)
          heardConsonant = laterMatch
          consumed += skip + laterMatch.length
          consonantMatched = true
        } else {
          // True mismatch — capture the digraph-aware consonant unit for reporting
          heardConsonant = identifyConsonantUnit(remaining)
          consumed += heardConsonant.length
        }
      }
    } else if (syl.vowel) {
      // No consonant expected (alef/ayin/silent final ה) but a vowel is.
      // Skim past any extra consonant the student inserted before the vowel.
      const vowelMatch = remaining.slice(0, 4).match(/[aeiouy]/)
      if (vowelMatch && vowelMatch.index > 0) {
        insertedBefore = remaining.slice(0, vowelMatch.index)
        consumed += vowelMatch.index
        consonantMatched = false // student inserted an unwanted consonant
      }
    }

    // -- Vowel phase --
    let vowelElongated = ''
    if (syl.vowel) {
      const afterConsonant = remaining.slice(consumed)
      const vMatch = pickVariant(afterConsonant, syl.vowelVariants ?? [syl.vowel], nextSyl)
      if (vMatch) {
        heardVowel = vMatch
        consumed += vMatch.length
        vowelMatched = true

        // Vowel-elongation: student held the vowel longer than written. Only
        // detect when the repeated char wouldn't legitimately belong to the
        // next audible syllable's vowel.
        const after = remaining.slice(consumed)
        const lastVowelChar = vMatch[vMatch.length - 1]
        const nextStartsWithSameVowel =
          nextSyl?.expected && nextSyl.expected[0] === lastVowelChar
        if (/[aeiouy]/.test(lastVowelChar) && !nextStartsWithSameVowel) {
          let extra = 0
          while (extra < 3 && after[extra] === lastVowelChar) extra++
          if (extra > 0) {
            vowelElongated = after.slice(0, extra)
            consumed += extra
          }
        }
      } else {
        // Vowel didn't match. Don't grab a vowel char that belongs to the
        // next audible syllable's expected sound (e.g. the "u" in "tsu" is
        // really for א+shuruk in וַיֵּצְאוּ — leave it for the next syllable).
        const expectedVowelLen = syl.vowel.length
        const vowelChars = afterConsonant.match(/^[aeiouy]+/)?.[0] ?? ''
        const wouldGrab = vowelChars.slice(0, expectedVowelLen)
        const nextStartsWithThis =
          wouldGrab && nextSyl?.expected && nextSyl.expected[0] === wouldGrab[0]
        if (!nextStartsWithThis) {
          heardVowel = wouldGrab
          consumed += heardVowel.length
        }
      }
    }

    // Decide status from the phase results
    let status
    if (consonantMatched && vowelMatched) {
      if (insertedBefore) status = 'matched-with-insertion'
      else if (vowelElongated) status = 'vowel-elongated'
      else status = 'matched'
    } else if (consonantMatched && !vowelMatched) {
      status = syl.vowel ? 'vowel-mismatch' : (heardVowel ? 'extra-vowel' : 'matched')
    } else if (!consonantMatched && vowelMatched && !syl.consonant) {
      // Silent expected consonant but student inserted one before the vowel
      status = 'extra-consonant'
    } else {
      status = 'mismatch'
    }

    matches.push({
      ...syl,
      status,
      heardAt: pos,
      heard: insertedBefore + heardConsonant + heardVowel + vowelElongated,
      heardConsonant,
      heardVowel,
      insertedBefore,
      vowelElongated,
      consonantMatched,
      vowelMatched,
    })
    pos += Math.max(1, consumed)
  }

  // Track if the student transcription has trailing chars not consumed (might
  // be a sheva nach inserted or extra sound at end)
  const trailing = student.slice(pos)
  return { matches, trailing }
}

// Patach genuvah syllables are vowel-then-consonant ("ach"), so the regular
// consonant-then-vowel phases don't fit. Called only after the accepted
// variants failed. Returns null to fall back to the generic phases.
function alignPatachGenuvah(syl, remaining) {
  const c = syl.consonant
  // Most common error: reading the patach after the letter ("rucha")
  if (c && cleanMatch(remaining, c + 'a')) {
    return {
      status: 'genuvah-reversed', heard: c + 'a', heardConsonant: c, heardVowel: 'a',
      consonantMatched: true, vowelMatched: false, consumed: c.length + 1,
    }
  }
  const heardVowel = remaining.match(/^[aeiouy]*/)[0]
  const afterVowel = remaining.slice(heardVowel.length)
  if (c && !cleanMatch(afterVowel, c)) return null
  return {
    status: 'vowel-mismatch', heard: heardVowel + (c ?? ''), heardConsonant: c, heardVowel,
    consonantMatched: true, vowelMatched: false, consumed: heardVowel.length + (c?.length ?? 0),
  }
}

// Per-syllable score derivation from the match status.
function scoreSyllable(m, tradition, shevaMode) {
  // Silent atoms (e.g. final silent ה) always score 100
  if (m.status === 'silent') return { score: 100, note: '' }

  if (m.status === 'matched') return { score: 95, note: '' }

  if (m.status === 'matched-with-insertion') {
    return {
      score: 78,
      note: `Extra "${m.insertedBefore}" sound inserted before ${m.atom.letter} — should not be there.`,
    }
  }

  if (m.status === 'vowel-elongated') {
    return {
      score: 80,
      note: `Vowel held too long — the "${m.vowel}" sound should not be elongated to "${m.vowel}${m.vowelElongated}".`,
    }
  }

  if (m.status === 'matched-after-skip') return { score: 90, note: '' }

  if (m.status === 'extra-vowel') {
    // Probably a sheva nach that was pronounced as vocal
    if (m.shevaType === 'nach' && shevaMode === 'enforce') {
      return {
        score: 68,
        note: `Sheva nach should be silent — heard an inserted "${m.heardVowel}" sound.`,
      }
    }
    return { score: 90, note: '' } // benign extra vowel
  }

  if (m.status === 'genuvah-reversed') {
    return {
      score: 75,
      note: `Patach genuvah — the "a" is said before the final ${m.atom.letter}: "${m.expected}", not "${m.heard}".`,
    }
  }

  if (m.status === 'vowel-mismatch') {
    // Consonant right, vowel different
    if (m.patachGenuvah) {
      return {
        score: 75,
        note: `Patach genuvah — a short "a" belongs before the final ${m.atom.letter} ("${m.expected}") — heard "${m.heard}".`,
      }
    }
    if (m.shevaType === 'na' && shevaMode === 'enforce' && !m.heardVowel) {
      return {
        score: 70,
        note: `Sheva na should be pronounced as a brief "uh" — the consonants ran together.`,
      }
    }
    if (m.shevaType === 'na' && shevaMode === 'enforce') {
      return {
        score: 75,
        note: `Sheva na should be a brief "e" / "uh" — heard "${m.heardVowel}".`,
      }
    }
    return {
      score: 75,
      note: `Vowel mismatch — expected "${m.expected}", heard "${m.heard}".`,
    }
  }

  if (m.status === 'extra-consonant') {
    const L = m.atom.letter
    const which = L === 'ה' ? 'silent ה' : L === 'א' ? 'silent א (alef)' : L === 'ע' ? 'silent ע (ayin)' : L
    return {
      score: 70,
      note: `Extra "${m.insertedBefore}" sound inserted before ${which} — that letter is silent here.`,
    }
  }

  if (m.status === 'mismatch') {
    const note = buildMismatchNote(m, tradition)
    return { score: 60, note }
  }

  return { score: 80, note: '' }
}

function buildMismatchNote(m, tradition) {
  const heardC = m.heardConsonant || m.heard
  const expectedC = m.consonant
  const L = m.atom.letter

  // Specific known errors with explanatory notes
  if (L === 'ת' && expectedC === 't' && heardC.startsWith('s')) {
    return `ת should be "t" (${tradition}) — heard "s" instead.`
  }
  if (L === 'ת' && expectedC === 's' && heardC.startsWith('t')) {
    return `ת without dagesh should be "s" (Ashkenazic sav) — heard "t" instead.`
  }
  if (L === 'ש' && expectedC === 'sh' && heardC.startsWith('s')) {
    return `שׁ (shin) should be "sh" — heard "s" instead.`
  }
  if (L === 'ש' && expectedC === 's' && heardC.startsWith('sh')) {
    return `שׂ (sin) should be "s" — heard "sh" instead.`
  }
  if (L === 'ב' && expectedC === 'b' && heardC.startsWith('v')) {
    return `בּ (with dagesh) should be "b" — heard "v" instead.`
  }
  if (L === 'ב' && expectedC === 'v' && heardC.startsWith('b')) {
    return `ב (no dagesh) should be "v" — heard "b" instead.`
  }
  if ((L === 'פ' || L === 'ף') && expectedC === 'p' && heardC.startsWith('f')) {
    return `פּ (with dagesh) should be "p" — heard "f" instead.`
  }
  if ((L === 'פ' || L === 'ף') && expectedC === 'f' && heardC.startsWith('p')) {
    return `פ (no dagesh) should be "f" — heard "p" instead.`
  }
  if (L === 'ה' && expectedC === 'h' && !heardC) {
    return `ה with mappiq should be pronounced "h" — heard silence.`
  }
  if (L === 'ה' && !expectedC && heardC.startsWith('h')) {
    return `Final ה should be silent here — heard "h".`
  }
  // Generic
  if (m.heard) return `${L} should be "${m.expected}" — heard "${m.heard}".`
  return `${L} expected sound was not heard.`
}

// Per-syllable sound breakdown for the sound-by-sound report. Each audible sound
// (the consonant letter and the vowel) is tagged correct/incorrect from the
// alignment. Silent sounds — alef/ayin, sheva nach, final silent ה — produce an
// empty Latin sound and are omitted, since they contribute no audible sound to
// count. `seg` is a syllable object carrying { consonant, vowel, atom }.
function makeBreakdown(seg, consonantCorrect, vowelCorrect) {
  return {
    consonant: seg.consonant
      ? { letter: seg.atom.letter, sound: seg.consonant, correct: consonantCorrect }
      : null,
    vowel: seg.vowel
      ? { name: seg.atom.vowel, sound: seg.vowel, correct: vowelCorrect }
      : null,
  }
}

// ── Public API ───────────────────────────────────────────────────────

// Score a single word: returns { word, score, errorType, phoneticHeard,
// expectedPhonetic, syllables: [{ phoneme, accuracyScore, note }] }
export function scoreWordAgainstTranscription(referenceWord, heardPhonetic, settings = {}) {
  const { tradition = 'sephardic', shevaMode = 'enforce' } = settings
  const atoms = tokenizeWord(referenceWord)
  const { segments, fullPhonetic } = getExpectedPhonetic(atoms, { tradition, shevaMode })
  const syllables = buildSyllables(atoms, segments)

  // No letters to grade (e.g. a stray punctuation token) — nothing to score
  if (syllables.length === 0) {
    return {
      word: referenceWord, score: 100, errorType: 'None',
      phoneticHeard: heardPhonetic ?? '', expectedPhonetic: '', syllables: [],
    }
  }

  // Omission: no heard phonetic at all
  if (!heardPhonetic || normalizeStudent(heardPhonetic).length === 0) {
    return {
      word: referenceWord,
      score: 0,
      errorType: 'Omission',
      phoneticHeard: '',
      expectedPhonetic: fullPhonetic,
      syllables: syllables.map(s => ({
        phoneme: s.display,
        accuracyScore: 0,
        note: '',
        breakdown: makeBreakdown(s, false, false),
      })),
    }
  }

  const { matches, trailing } = alignSyllables(syllables, heardPhonetic)

  const scoredSyllables = matches.map(m => {
    const { score, note } = scoreSyllable(m, tradition, shevaMode)
    const breakdown = makeBreakdown(m, !!m.consonantMatched, !!m.vowelMatched)
    return { phoneme: m.display, accuracyScore: score, note, breakdown, _match: m }
  })

  // Penalize any trailing chars the student said after the word's expected end.
  // Attach the note to the last audible syllable so it's visible in the panel.
  if (trailing) {
    for (let i = scoredSyllables.length - 1; i >= 0; i--) {
      if (scoredSyllables[i]._match.expected) {
        const ex = scoredSyllables[i]
        const trailingNote = `Extra "${trailing}" sound at the end of the word — should not be there.`
        scoredSyllables[i] = {
          ...ex,
          accuracyScore: Math.min(ex.accuracyScore, 78),
          note: ex.note ? `${ex.note} ${trailingNote}` : trailingNote,
        }
        break
      }
    }
  }

  const avgScore = Math.round(
    scoredSyllables.reduce((s, x) => s + x.accuracyScore, 0) / scoredSyllables.length
  )
  const anyErrors = scoredSyllables.some(s => s.accuracyScore < 85)
  const errorType = anyErrors ? 'Mispronunciation' : 'None'

  // Strip the internal _match field before returning
  return {
    word: referenceWord,
    score: avgScore,
    errorType,
    phoneticHeard: heardPhonetic,
    expectedPhonetic: fullPhonetic,
    syllables: scoredSyllables.map(({ _match, ...rest }) => rest),
  }
}

// Score an entire utterance: word-by-word using provided per-word transcriptions.
export function scoreWords(referenceWords, perWordHeard, settings = {}) {
  return referenceWords.map((word, i) => scoreWordAgainstTranscription(word, perWordHeard[i] ?? '', settings))
}
